name: Publish Expo Go Preview Update

on:
  push:
    branches: ['dev']
    paths:
      - mobile_frontend/**

jobs:
  publish_update:
    name: Publish Expo Go Preview Update
    type: update
    params:
      branch: dev
